import os
import math

import torch
from torch.utils.data import random_split
from torch_geometric.datasets import TUDataset
from torch_geometric.data import DataLoader
from torch_geometric.data import Dataset as PyGDataset
import os.path as osp

from MotiFiesta.utils.synthetic import SyntheticMotifs
from MotiFiesta.utils.real_world import RealWorldDataset
from MotiFiesta.utils.sys_txt import SysTxtDataset
from MotiFiesta.utils.sys_synthetic import SysSyntheticDataset
from MotiFiesta.utils.sys_loader import SysLoader
from MotiFiesta.utils.bfs_decompose import BFSDecomposedDataset, LouvainDecomposedDataset, PrebuiltPairsDataset


class PrebuiltPairsDataset(PyGDataset):
    """loads pre-built pos/neg pair files from root/processed/data_{i}.pt.

    used for synth_pairs datasets generated by build_synth_data.py.
    does not regenerate data — expects processed/ to already exist.
    """
    def __init__(self, root):
        self._root = root
        proc_dir = osp.join(root, 'processed')
        self._cached_files = sorted(
            [f for f in os.listdir(proc_dir) if f.startswith('data_') and f.endswith('.pt')]
        )
        super().__init__(root)

    @property
    def processed_file_names(self):
        return self._cached_files

    def process(self):
        pass  # data already built by build_synth_data.py

    def len(self):
        return len(self.processed_file_names)

    def get(self, idx):
        fname = self.processed_file_names[idx]
        return torch.load(osp.join(self.processed_dir, fname), weights_only=False)

    @property
    def num_features(self):
        sample = self.get(0)
        return sample['pos'].x.size(1)


def get_loader(root,
               name='synthetic',
               batch_size=2,
               **kwargs
               ):
    """
    Arguments
    ----------
    root:
        path to folder for storing the dataset
    name:
        ID of dataset (options: 'synthetic' generates synthetic motifs, else the string ID of a PyG dataset

    Returns
    -------

    dict:
        Dictionary with loaders and datasets for train/test

    """
    if name == 'synth_pairs':
        dataset = PrebuiltPairsDataset(root=root)
    elif not name.startswith('synth'):
        if name == 'IMDB-BINARY':
            dataset = RealWorldDataset(root=name, max_degree=300, n_features=301)
        else:
            dataset = RealWorldDataset(root=name)
    else:
        print(">>> FAIL: Falling back to RealWorldDataset")
        if not name.startswith('synth'):
            if name == 'IMDB-BINARY':
                dataset = RealWorldDataset(root=root, max_degree=300, n_features=301)
            else:
                dataset = RealWorldDataset(root=root)
        else:
            dataset = SyntheticMotifs(root=root, name=name, **kwargs)
    if len(dataset) <= 1:
        # no split for a systems-level graph
        # same dataset for both, masks for train/test
        print("systems-level graph detected: skipping dataset split")
        # calculate split indices
        num_nodes = dataset[0].num_nodes
        indices = torch.randperm(num_nodes, generator=torch.Generator().manual_seed(42))
        split_idx = int(num_nodes * 0.8)

        # degree-biased seed sampling: high-degree nodes (motif nodes) are
        # sampled as seeds proportionally more often, so training batches are
        # more frequently centered on motif instances. test and decode loaders
        # stay uniform so evaluation is unbiased.
        data = dataset[0]
        degrees = data.edge_index[0].bincount(minlength=num_nodes).float()
        train_idx = torch.multinomial(
            degrees + 1.0,
            num_samples=split_idx,
            replacement=True,
            generator=torch.Generator().manual_seed(42),
        )
        test_idx = indices[split_idx:]

        # 1-hop neighborhood: captures one complete motif instance from a motif seed
        motif_size = int(kwargs.get('motif_size', 10))
        num_neighbors = [motif_size - 1, 0]

        loader_train = SysLoader(dataset[0], input_nodes=train_idx, batch_size=batch_size, num_neighbors=num_neighbors, shuffle=True)
        loader_test = SysLoader(dataset[0], input_nodes=test_idx, batch_size=batch_size, num_neighbors=num_neighbors, shuffle=True)
        loader = SysLoader(dataset[0], batch_size=batch_size, num_neighbors=num_neighbors, shuffle=False)
    else:
        lengths = [math.floor(len(dataset) * .8), math.ceil(len(dataset) * .2)]
        train_data, test_data = random_split(dataset, lengths, generator=torch.Generator().manual_seed(42))
        loader_train = DataLoader(train_data, batch_size=batch_size, shuffle=True)
        loader_test = DataLoader(test_data, batch_size=batch_size, shuffle=True)
        loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)
    return {'dataset_whole': dataset, 'loader_whole': loader, 'loader_train': loader_train, 'loader_test': loader_test}


if __name__ == "__main__":
    data = get_loader(root='barbell-pair')
    print(data)
