import os
import math
import os.path as osp

import torch
from torch.utils.data import random_split
from torch_geometric.datasets import TUDataset
from torch_geometric.data import DataLoader
from torch_geometric.data import Dataset as PyGDataset

from MotiFiesta.utils.synthetic import SyntheticMotifs
from MotiFiesta.utils.real_world import RealWorldDataset


class PrebuiltPairsDataset(PyGDataset):
    """loads pre-built pos/neg pair files from root/processed/data_{i}.pt.
    expects processed/ to already exist, generated by build_synth_data.py."""
    def __init__(self, root):
        self._root = root
        proc_dir = osp.join(root, 'processed')
        self._cached_files = sorted(
            [f for f in os.listdir(proc_dir) if f.startswith('data_') and f.endswith('.pt')]
        )
        super().__init__(root)

    @property
    def processed_file_names(self):
        return self._cached_files

    def process(self):
        pass

    def len(self):
        return len(self.processed_file_names)

    def get(self, idx):
        fname = self.processed_file_names[idx]
        return torch.load(osp.join(self.processed_dir, fname), weights_only=False)

    @property
    def num_features(self):
        return self.get(0)['pos'].x.size(1)


def get_loader(root,
               name='synthetic',
               batch_size=2,
               **kwargs
               ):
    """
    Arguments
    ----------
    root:
        path to folder for storing the dataset
    name:
        ID of dataset (options: 'synth_pairs' for pre-built pairs, else a PyG dataset ID)

    Returns
    -------
    dict:
        Dictionary with loaders and datasets for train/test
    """
    if name == 'synth_pairs':
        dataset = PrebuiltPairsDataset(root=root)
    elif not name.startswith('synth'):
        if name == 'IMDB-BINARY':
            dataset = RealWorldDataset(root=root, max_degree=300, n_features=301)
        else:
            dataset = RealWorldDataset(root=root)
    else:
        dataset = SyntheticMotifs(root=root, name=name, **kwargs)

    lengths = [math.floor(len(dataset) * .8), math.ceil(len(dataset) * .2)]
    train_data, test_data = random_split(dataset, lengths, generator=torch.Generator().manual_seed(42))
    loader_train = DataLoader(train_data, batch_size=batch_size, shuffle=True)
    loader_test  = DataLoader(test_data,  batch_size=batch_size, shuffle=True)
    loader       = DataLoader(dataset,    batch_size=batch_size, shuffle=False)
    return {'dataset_whole': dataset, 'loader_whole': loader,
            'loader_train': loader_train, 'loader_test': loader_test}


if __name__ == "__main__":
    data = get_loader(root='barbell-pair')
    print(data)
